build:
	-mkdir .jclass
	javac -cp ".:./argparse4j-0.9.0.jar" -d .jclass Main.java

clean:
	rm -rf .jclass

jar:
	wget https://github.com/argparse4j/argparse4j/releases/download/argparse4j-0.9.0/argparse4j-0.9.0.jar
